// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9UNCdLS_0H9wfAEaHX0QUEftTcdmy-7g',
    appId: '1:206182314858:web:add8ef3267085f5875ab13',
    databaseURL:
        'https://studyatapp-default-rtdb.europe-west1.firebasedatabase.app',
    messagingSenderId: '206182314858',
    projectId: 'studyatapp',
    authDomain: 'studyatapp.firebaseapp.com',
    storageBucket: 'studyatapp.appspot.com',
    measurementId: 'G-48X51SXT0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIdFDn75aSB6zm6LiRKxZ0k9ZCyr8j5ho',
    appId: '1:206182314858:android:a9e8effc89c2801675ab13',
    databaseURL:
        'https://studyatapp-default-rtdb.europe-west1.firebasedatabase.app',
    messagingSenderId: '206182314858',
    projectId: 'studyatapp',
    storageBucket: 'studyatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5t_Z_WN1S-A34emf4PLw4XLUkN8wPh8k',
    appId: '1:206182314858:ios:ecebedd18c121a3a75ab13',
    databaseURL:
        'https://studyatapp-default-rtdb.europe-west1.firebasedatabase.app',
    messagingSenderId: '206182314858',
    projectId: 'studyatapp',
    storageBucket: 'studyatapp.appspot.com',
    iosBundleId: 'com.example.studyAt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5t_Z_WN1S-A34emf4PLw4XLUkN8wPh8k',
    appId: '1:206182314858:ios:e30410f29a20ab9175ab13',
    databaseURL:
        'https://studyatapp-default-rtdb.europe-west1.firebasedatabase.app',
    messagingSenderId: '206182314858',
    projectId: 'studyatapp',
    storageBucket: 'studyatapp.appspot.com',
    iosBundleId: 'com.example.studyAt.RunnerTests',
  );
}
